<?php
global $lang, $app;
if(empty($lang->jxcore->statusList ?? null)) $app->loadLang('jxcore');
$config->jxmarketaccess->dtable = new stdclass();
$config->jxmarketaccess->dtable->fieldList['id']['name']   = 'id';
$config->jxmarketaccess->dtable->fieldList['id']['title']  = $lang->idAB;
$config->jxmarketaccess->dtable->fieldList['id']['type']   = 'id';
$config->jxmarketaccess->dtable->fieldList['name']['name'] = 'name';
$config->jxmarketaccess->dtable->fieldList['name']['title']= $lang->jxmarketaccess->name;
$config->jxmarketaccess->dtable->fieldList['name']['type'] = 'title';
$config->jxmarketaccess->dtable->fieldList['name']['link'] = array('module' => 'jxmarketaccess', 'method' => 'view', 'params' => 'id={id}');
$config->jxmarketaccess->dtable->fieldList['name']['flex'] = 1;
$config->jxmarketaccess->dtable->fieldList['code']['name'] = 'code';
$config->jxmarketaccess->dtable->fieldList['code']['title']= $lang->jxmarketaccess->code;
$config->jxmarketaccess->dtable->fieldList['code']['type'] = 'text';
$config->jxmarketaccess->dtable->fieldList['productName']['name']  = 'productName';
$config->jxmarketaccess->dtable->fieldList['productName']['title'] = $lang->jxmarketaccess->product;
$config->jxmarketaccess->dtable->fieldList['productName']['type']  = 'text';
$config->jxmarketaccess->dtable->fieldList['type']['name']  = 'type';
$config->jxmarketaccess->dtable->fieldList['type']['title'] = $lang->jxmarketaccess->type;
$config->jxmarketaccess->dtable->fieldList['type']['type']  = 'text';
$config->jxmarketaccess->dtable->fieldList['type']['map']   = $lang->jxmarketaccess->typeList;
$config->jxmarketaccess->dtable->fieldList['region']['name']  = 'region';
$config->jxmarketaccess->dtable->fieldList['region']['title'] = $lang->jxmarketaccess->region;
$config->jxmarketaccess->dtable->fieldList['region']['type']  = 'text';
$config->jxmarketaccess->dtable->fieldList['windowEnd']['name']  = 'windowEnd';
$config->jxmarketaccess->dtable->fieldList['windowEnd']['title'] = $lang->jxmarketaccess->windowEnd;
$config->jxmarketaccess->dtable->fieldList['windowEnd']['type']  = 'date';
$config->jxmarketaccess->dtable->fieldList['status']['name']  = 'status';
$config->jxmarketaccess->dtable->fieldList['status']['title'] = $lang->jxmarketaccess->status;
$config->jxmarketaccess->dtable->fieldList['status']['type']  = 'status';
$config->jxmarketaccess->dtable->fieldList['status']['statusMap'] = $lang->jxcore->statusList;
$config->jxmarketaccess->dtable->fieldList['progress']['name']  = 'progress';
$config->jxmarketaccess->dtable->fieldList['progress']['title'] = $lang->jxcore->progress;
$config->jxmarketaccess->dtable->fieldList['progress']['type']  = 'progress';
$config->jxmarketaccess->dtable->fieldList['health']['name']  = 'health';
$config->jxmarketaccess->dtable->fieldList['health']['title'] = $lang->jxcore->health;
$config->jxmarketaccess->dtable->fieldList['health']['type']  = 'text';
$config->jxmarketaccess->dtable->fieldList['health']['map']   = $lang->jxcore->healthList;
