<?php
global $lang, $app;
if(empty($lang->jxcore->statusList ?? null)) $app->loadLang('jxcore');
$config->jxadmission->dtable = new stdclass();
$config->jxadmission->dtable->fieldList['id']['name'] = 'id';
$config->jxadmission->dtable->fieldList['id']['title'] = $lang->idAB;
$config->jxadmission->dtable->fieldList['id']['type'] = 'id';
$config->jxadmission->dtable->fieldList['name']['name'] = 'name';
$config->jxadmission->dtable->fieldList['name']['title'] = $lang->jxadmission->name;
$config->jxadmission->dtable->fieldList['name']['type'] = 'title';
$config->jxadmission->dtable->fieldList['name']['link'] = array('module' => 'jxadmission', 'method' => 'view', 'params' => 'id={id}');
$config->jxadmission->dtable->fieldList['name']['flex'] = 1;
$config->jxadmission->dtable->fieldList['productName']['name'] = 'productName';
$config->jxadmission->dtable->fieldList['productName']['title'] = $lang->jxadmission->product;
$config->jxadmission->dtable->fieldList['productName']['type'] = 'text';
$config->jxadmission->dtable->fieldList['hospitalName']['name'] = 'hospitalName';
$config->jxadmission->dtable->fieldList['hospitalName']['title'] = $lang->jxadmission->hospital;
$config->jxadmission->dtable->fieldList['hospitalName']['type'] = 'text';
$config->jxadmission->dtable->fieldList['department']['name'] = 'department';
$config->jxadmission->dtable->fieldList['department']['title'] = $lang->jxadmission->department;
$config->jxadmission->dtable->fieldList['department']['type'] = 'text';
$config->jxadmission->dtable->fieldList['status']['name'] = 'status';
$config->jxadmission->dtable->fieldList['status']['title'] = $lang->jxadmission->status;
$config->jxadmission->dtable->fieldList['status']['type'] = 'status';
$config->jxadmission->dtable->fieldList['status']['statusMap'] = $lang->jxcore->statusList;
$config->jxadmission->dtable->fieldList['progress']['name'] = 'progress';
$config->jxadmission->dtable->fieldList['progress']['title'] = $lang->jxcore->progress;
$config->jxadmission->dtable->fieldList['progress']['type'] = 'progress';
$config->jxadmission->dtable->fieldList['health']['name'] = 'health';
$config->jxadmission->dtable->fieldList['health']['title'] = $lang->jxcore->health;
$config->jxadmission->dtable->fieldList['health']['type'] = 'text';
$config->jxadmission->dtable->fieldList['health']['map'] = $lang->jxcore->healthList;
$config->jxadmission->dtable->fieldList['volume']['name'] = 'volume';
$config->jxadmission->dtable->fieldList['volume']['title'] = $lang->jxadmission->volume;
$config->jxadmission->dtable->fieldList['volume']['type'] = 'number';
